OPENAI_STATE_PENDING = "pending"
OPENAI_STATE_SUBMITTED = "submitted"
OPENAI_STATE_COMPLETED = "completed"
OPENAI_STATE_FAILED = "failed"
OPENAI_STATE_INCOMPLETE = "incomplete"
OPENAI_STATE_CANCELLED = "cancelled"

TERMINAL_OPENAI_STATES = frozenset(
    {
        OPENAI_STATE_COMPLETED,
        OPENAI_STATE_FAILED,
        OPENAI_STATE_INCOMPLETE,
        OPENAI_STATE_CANCELLED,
    }
)

POSTPROCESS_STATE_NOT_STARTED = "not_started"
POSTPROCESS_STATE_FETCH_PENDING = "fetch_pending"
POSTPROCESS_STATE_FETCH_IN_PROGRESS = "fetch_in_progress"
POSTPROCESS_STATE_FETCH_FAILED = "fetch_failed"
POSTPROCESS_STATE_NOTIFY_PENDING = "notify_pending"
POSTPROCESS_STATE_NOTIFY_IN_PROGRESS = "notify_in_progress"
POSTPROCESS_STATE_NOTIFY_FAILED = "notify_failed"
POSTPROCESS_STATE_NOTIFY_SUCCEEDED = "notify_succeeded"
POSTPROCESS_STATE_NOT_REQUIRED = "not_required"

POSTPROCESS_ACTIVE_STATES = frozenset(
    {
        POSTPROCESS_STATE_FETCH_PENDING,
        POSTPROCESS_STATE_FETCH_FAILED,
        POSTPROCESS_STATE_NOTIFY_PENDING,
        POSTPROCESS_STATE_NOTIFY_FAILED,
    }
)
